### ISSUE TITLE
PCSX4's use of XVisor violates GPLv2

### ISSUE THREAD

**Issue by baconwaifu** [pcsx4emudev/xvisor-iommu-emulation-framework#1]
If the core PCSX4 executable does not have published source (which it does not) then it can't use *any* GPLv2 licensed code. Given that XVisor is licensed under GPLv2, your only option is to immediately discontinue distribution, *AND* provide the source to any released versions compliant to the license.

The relevant provisions of the GPLv2 are sections 2 and 3: Derivative works must be licensed under GPLv2, and source code for GPLv2 works that are distributed *must be published*.

PS: the terms on the website restricting redistribution, reverse engineering, and modification are in blatant violation of GPLv2 section 6

**Comment by baconwaifu** [comment]
...Fucking scammers. project isn't real to begin with.

**Comment by blacklat** [comment]
this project is fake
